package com.freetime.freedroid.ui

import androidx.compose.ui.graphics.Color

// Generated by the Material Theme Builder with modern Droid-ify inspired colors
// https://www.figma.com/community/plugin/1034969338659738588
// Clean, modern Material Design 3 color scheme

val primaryLight = Color(0xFF1976D2) // Modern Blue
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE3F2FD) // Light Blue Container
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF455A64) // Modern Blue-Gray
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFECEFF1) // Light Gray Container
val onSecondaryContainerLight = Color(0xFF1C2700)
val tertiaryLight = Color(0xFF7E57C2) // Modern Purple
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEDE7F6) // Light Purple Container
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAFAFA) // Clean White
val onBackgroundLight = Color(0xFF181C21)
val surfaceLight = Color(0xFFFFFFFF) // Pure White Surface
val onSurfaceLight = Color(0xFF181C21)
val surfaceVariantLight = Color(0xFFF5F5F5) // Light Surface Variant
val onSurfaceVariantLight = Color(0xFF414752)
val outlineLight = Color(0xFF717783)
val outlineVariantLight = Color(0xFFC1C6D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3037)
val inverseOnSurfaceLight = Color(0xFFEFF0F9)
val inversePrimaryLight = Color(0xFFA5C8FF)
val surfaceDimLight = Color(0xFFD8DAE2)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3FC)
val surfaceContainerLight = Color(0xFFECEDF6)
val surfaceContainerHighLight = Color(0xFFE6E8F0)
val surfaceContainerHighestLight = Color(0xFFE0E2EA)

val primaryDark = Color(0xFF90CAF9) // Light Blue for Dark Theme
val onPrimaryDark = Color(0xFF00315F)
val primaryContainerDark = Color(0xFF1565C0) // Dark Blue Container
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFF90A4AE) // Light Blue-Gray for Dark Theme
val onSecondaryDark = Color(0xFF283500)
val secondaryContainerDark = Color(0xFF37474F) // Dark Gray Container
val onSecondaryContainerDark = Color(0xFF080D00)
val tertiaryDark = Color(0xFFBA68C8) // Light Purple for Dark Theme
val onTertiaryDark = Color(0xFF52046E)
val tertiaryContainerDark = Color(0xFF6A1B9A) // Dark Purple Container
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121212) // Material Dark Background
val onBackgroundDark = Color(0xFFE0E2EA)
val surfaceDark = Color(0xFF1E1E1E) // Material Dark Surface
val onSurfaceDark = Color(0xFFE0E2EA)
val surfaceVariantDark = Color(0xFF2C2C2C) // Dark Surface Variant
val onSurfaceVariantDark = Color(0xFFC1C6D4)
val outlineDark = Color(0xFF8B919E)
val outlineVariantDark = Color(0xFF414752)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2EA)
val inverseOnSurfaceDark = Color(0xFF2D3037)
val inversePrimaryDark = Color(0xFF005FAF)
val surfaceDimDark = Color(0xFF101319)
val surfaceBrightDark = Color(0xFF363940)
val surfaceContainerLowestDark = Color(0xFF0B0E14)
val surfaceContainerLowDark = Color(0xFF181C21)
val surfaceContainerDark = Color(0xFF222222) // Dark Container
val surfaceContainerHighDark = Color(0xFF2A2A2A) // Dark High Container
val surfaceContainerHighestDark = Color(0xFF333333) // Dark Highest Container
